services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UserBundle\:
        resource: '../../*'
        exclude: '../../{Entity}'

    UserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    UserBundle\Doctrine\UserManager:
        public: true
        arguments:
            $class: '%user.user_class%'
        calls:
            - method: setEncoder
              arguments:
                  - '@security.password_encoder'

    UserBundle\Security\UserProvider:
        arguments:
            $class: '%user.user_class%'

    UserBundle\Security\LoginFormAuthenticator:
        arguments:
            $defaultTargetPath: '%user.login.default_target_path%'
